package com.lance.model;

import com.lance.model.common.LanceAdminAM;
import com.lance.model.vo.JobCategoryVOImpl;
import com.lance.model.vo.JobSubCategoryVOImpl;
import com.lance.model.vo.JobTemplateVOImpl;

import com.lance.model.vo.SysCalendarVOImpl;

import com.lance.model.vo.SysCalendarVORowImpl;

import com.zngh.platform.front.core.model.BaseApplicationModuleImpl;


import java.text.SimpleDateFormat;

import java.util.Calendar;
import java.util.Date;

import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 04 15:20:01 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LanceAdminAMImpl extends BaseApplicationModuleImpl implements LanceAdminAM {
    /**
     * This is the default constructor (do not remove).
     */
    public LanceAdminAMImpl() {
    }

    /**
     * 创建当前日期往后指定时间内的时间。
     * @return
     */
    public String createSysCalendarDates(Integer start, Integer end) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        SysCalendarVOImpl vo = this.getSysCalendar1();
        SysCalendarVORowImpl row;
        for (int i = start; i <= end; i++) {
            row = (SysCalendarVORowImpl) vo.createRow();
            c.add(Calendar.DAY_OF_YEAR, 1);
            Date date = c.getTime();
            System.out.println(sdf.format(date) + ":" + getWeekOfDate(date));
            row.setSysDateRec(sdf.format(date));
            row.setDay(getWeekOfDate(date));
            row.setShowOrder((long) i);
            if (row.getDay().equals(7) || row.getDay().equals(6)) {
                row.setDateType("SDT_WEEKEND");
            } else {
                row.setDateType("SDT_WORK");
            }
            vo.insertRow(row);
        }
        return "ok";
    }


    public Integer getWeekOfDate(Date dt) {
        Integer[] weekDays = { 7, 1, 2, 3, 4, 5, 6 };
        Calendar cal = Calendar.getInstance();
        cal.setTime(dt);
        int w = cal.get(Calendar.DAY_OF_WEEK) - 1;
        if (w < 0)
            w = 0;
        return weekDays[w];
    }

    /**
     * Container's getter for JobCategory1.
     * @return JobCategory1
     */
    public JobCategoryVOImpl getJobCategory1() {
        return (JobCategoryVOImpl) findViewObject("JobCategory1");
    }

    /**
     * Container's getter for JobTemplate1.
     * @return JobTemplate1
     */
    public JobTemplateVOImpl getJobTemplate1() {
        return (JobTemplateVOImpl) findViewObject("JobTemplate1");
    }

    /**
     * Container's getter for JobTemplate2.
     * @return JobTemplate2
     */
    public JobTemplateVOImpl getJobTemplate2() {
        return (JobTemplateVOImpl) findViewObject("JobTemplate2");
    }

    /**
     * Container's getter for JobSubCategory1.
     * @return JobSubCategory1
     */
    public JobSubCategoryVOImpl getJobSubCategory1() {
        return (JobSubCategoryVOImpl) findViewObject("JobSubCategory1");
    }

    /**
     * Container's getter for SysCalendar1.
     * @return SysCalendar1
     */
    public SysCalendarVOImpl getSysCalendar1() {
        return (SysCalendarVOImpl) findViewObject("SysCalendar1");
    }

    /**
     * Container's getter for JobTemplateJobCategoryFk1VL1.
     * @return JobTemplateJobCategoryFk1VL1
     */
    public ViewLinkImpl getJobTemplateJobCategoryFk1VL1() {
        return (ViewLinkImpl) findViewLink("JobTemplateJobCategoryFk1VL1");
    }

    /**
     * Container's getter for JobCategory_SubCategoryVL1.
     * @return JobCategory_SubCategoryVL1
     */
    public ViewLinkImpl getJobCategory_SubCategoryVL1() {
        return (ViewLinkImpl) findViewLink("JobCategory_SubCategoryVL1");
    }
}

