SET SQLBLANKLINES ON
ALTER TABLE JOB_SUB_CATEGORY_HIS 
RENAME TO JOB_SUB_CATEGORY_SUBMIT;

ALTER TABLE JOB_TEMPLATE 
ADD (IS_DEFAULT VARCHAR2(1 CHAR) );

ALTER TABLE JOB_TEMPLATE MOVE 
LOB (DESCRIPTION_CN) STORE AS SYS_LOB0000030301C00005$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE JOB_TEMPLATE MOVE 
LOB (DESCRIPTION_EN) STORE AS SYS_LOB0000030301C00006$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  STORAGE 
  ( 
    INITIAL 65536 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
);

ALTER TABLE JOB_SUB_CATEGORY_EXPERTS
ADD CONSTRAINT JOB_SUB_CATEGORY_EXPERTS_FK1 FOREIGN KEY
(
  SUB_CATEGORY_ID 
)
REFERENCES JOB_SUB_CATEGORY
(
  UUID 
)
ENABLE;

ALTER TABLE JOB_SUB_CATEGORY_SUBMIT
ADD CONSTRAINT JOB_SUB_CATEGORY_HIS_FK1 FOREIGN KEY
(
  SUB_CATEGORY_ID 
)
REFERENCES JOB_SUB_CATEGORY
(
  UUID 
)
ENABLE;

COMMENT ON TABLE JOB_SUB_CATEGORY_SUBMIT IS '修改SubCategory的申请';

COMMENT ON COLUMN JOB_TEMPLATE.IS_DEFAULT IS '是否默认';
