package com.lance.model.vo;

import com.lance.model.eo.CompanyEOImpl;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 01 18:02:28 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyVORowImpl extends BaseViewRowImpl {


    public static final int ENTITY_COMPANYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        Name,
        EnterpriseProperty,
        EmployeeNumberGrade,
        FoundYear,
        AboutCompany,
        ServiceDesc,
        Location,
        LocationCity,
        LocationCountry,
        LocationDesc,
        LocationProvince,
        Video,
        Logo,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int ENTERPRISEPROPERTY = AttributesEnum.EnterpriseProperty.index();
    public static final int EMPLOYEENUMBERGRADE = AttributesEnum.EmployeeNumberGrade.index();
    public static final int FOUNDYEAR = AttributesEnum.FoundYear.index();
    public static final int ABOUTCOMPANY = AttributesEnum.AboutCompany.index();
    public static final int SERVICEDESC = AttributesEnum.ServiceDesc.index();
    public static final int LOCATION = AttributesEnum.Location.index();
    public static final int LOCATIONCITY = AttributesEnum.LocationCity.index();
    public static final int LOCATIONCOUNTRY = AttributesEnum.LocationCountry.index();
    public static final int LOCATIONDESC = AttributesEnum.LocationDesc.index();
    public static final int LOCATIONPROVINCE = AttributesEnum.LocationProvince.index();
    public static final int VIDEO = AttributesEnum.Video.index();
    public static final int LOGO = AttributesEnum.Logo.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CompanyVORowImpl() {
    }

    /**
     * Gets CompanyEO entity object.
     * @return the CompanyEO
     */
    public CompanyEOImpl getCompanyEO() {
        return (CompanyEOImpl) getEntity(ENTITY_COMPANYEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for ENTERPRISE_PROPERTY using the alias name EnterpriseProperty.
     * @return the ENTERPRISE_PROPERTY
     */
    public String getEnterpriseProperty() {
        return (String) getAttributeInternal(ENTERPRISEPROPERTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTERPRISE_PROPERTY using the alias name EnterpriseProperty.
     * @param value value to set the ENTERPRISE_PROPERTY
     */
    public void setEnterpriseProperty(String value) {
        setAttributeInternal(ENTERPRISEPROPERTY, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NUMBER_GRADE using the alias name EmployeeNumberGrade.
     * @return the EMPLOYEE_NUMBER_GRADE
     */
    public Number getEmployeeNumberGrade() {
        return (Number) getAttributeInternal(EMPLOYEENUMBERGRADE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER_GRADE using the alias name EmployeeNumberGrade.
     * @param value value to set the EMPLOYEE_NUMBER_GRADE
     */
    public void setEmployeeNumberGrade(Number value) {
        setAttributeInternal(EMPLOYEENUMBERGRADE, value);
    }

    /**
     * Gets the attribute value for FOUND_YEAR using the alias name FoundYear.
     * @return the FOUND_YEAR
     */
    public Date getFoundYear() {
        return (Date) getAttributeInternal(FOUNDYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for FOUND_YEAR using the alias name FoundYear.
     * @param value value to set the FOUND_YEAR
     */
    public void setFoundYear(Date value) {
        setAttributeInternal(FOUNDYEAR, value);
    }

    /**
     * Gets the attribute value for ABOUT_COMPANY using the alias name AboutCompany.
     * @return the ABOUT_COMPANY
     */
    public String getAboutCompany() {
        return (String) getAttributeInternal(ABOUTCOMPANY);
    }

    /**
     * Sets <code>value</code> as attribute value for ABOUT_COMPANY using the alias name AboutCompany.
     * @param value value to set the ABOUT_COMPANY
     */
    public void setAboutCompany(String value) {
        setAttributeInternal(ABOUTCOMPANY, value);
    }

    /**
     * Gets the attribute value for SERVICE_DESC using the alias name ServiceDesc.
     * @return the SERVICE_DESC
     */
    public String getServiceDesc() {
        return (String) getAttributeInternal(SERVICEDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for SERVICE_DESC using the alias name ServiceDesc.
     * @param value value to set the SERVICE_DESC
     */
    public void setServiceDesc(String value) {
        setAttributeInternal(SERVICEDESC, value);
    }

    /**
     * Gets the attribute value for LOCATION using the alias name Location.
     * @return the LOCATION
     */
    public String getLocation() {
        return (String) getAttributeInternal(LOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION using the alias name Location.
     * @param value value to set the LOCATION
     */
    public void setLocation(String value) {
        setAttributeInternal(LOCATION, value);
    }

    /**
     * Gets the attribute value for LOCATION_CITY using the alias name LocationCity.
     * @return the LOCATION_CITY
     */
    public String getLocationCity() {
        return (String) getAttributeInternal(LOCATIONCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_CITY using the alias name LocationCity.
     * @param value value to set the LOCATION_CITY
     */
    public void setLocationCity(String value) {
        setAttributeInternal(LOCATIONCITY, value);
    }

    /**
     * Gets the attribute value for LOCATION_COUNTRY using the alias name LocationCountry.
     * @return the LOCATION_COUNTRY
     */
    public String getLocationCountry() {
        return (String) getAttributeInternal(LOCATIONCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_COUNTRY using the alias name LocationCountry.
     * @param value value to set the LOCATION_COUNTRY
     */
    public void setLocationCountry(String value) {
        setAttributeInternal(LOCATIONCOUNTRY, value);
    }

    /**
     * Gets the attribute value for LOCATION_DESC using the alias name LocationDesc.
     * @return the LOCATION_DESC
     */
    public String getLocationDesc() {
        return (String) getAttributeInternal(LOCATIONDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_DESC using the alias name LocationDesc.
     * @param value value to set the LOCATION_DESC
     */
    public void setLocationDesc(String value) {
        setAttributeInternal(LOCATIONDESC, value);
    }

    /**
     * Gets the attribute value for LOCATION_PROVINCE using the alias name LocationProvince.
     * @return the LOCATION_PROVINCE
     */
    public String getLocationProvince() {
        return (String) getAttributeInternal(LOCATIONPROVINCE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_PROVINCE using the alias name LocationProvince.
     * @param value value to set the LOCATION_PROVINCE
     */
    public void setLocationProvince(String value) {
        setAttributeInternal(LOCATIONPROVINCE, value);
    }

    /**
     * Gets the attribute value for VIDEO using the alias name Video.
     * @return the VIDEO
     */
    public String getVideo() {
        return (String) getAttributeInternal(VIDEO);
    }

    /**
     * Sets <code>value</code> as attribute value for VIDEO using the alias name Video.
     * @param value value to set the VIDEO
     */
    public void setVideo(String value) {
        setAttributeInternal(VIDEO, value);
    }

    /**
     * Gets the attribute value for LOGO using the alias name Logo.
     * @return the LOGO
     */
    public String getLogo() {
        return (String) getAttributeInternal(LOGO);
    }

    /**
     * Sets <code>value</code> as attribute value for LOGO using the alias name Logo.
     * @param value value to set the LOGO
     */
    public void setLogo(String value) {
        setAttributeInternal(LOGO, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }
}

