package com.lance.model.vo;

import com.lance.model.eo.ContractEOImpl;

import com.zngh.platform.front.core.model.BaseEntityImpl;

import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 13 16:35:57 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractVORowImpl extends BaseViewRowImpl {


    public static final int ENTITY_CONTRACTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        AttachmentLink,
        ClientCompanyId,
        ClientCompanyName,
        ClientConfirmDelayDay,
        ClientEmail,
        ClientIdNo,
        ClientIdType,
        ClientName,
        ClientSignBy,
        ClientPayDelayDay,
        ClientPhone,
        ClientRoleTitle,
        ClientTotalScore,
        ClientTrueName,
        Content,
        CreateBy,
        CreateOn,
        DateEnd,
        DateStart,
        FixedPayDate,
        FixedPayDelayHoliday,
        FixedPayPrice,
        HourlyPay,
        LancerCompanyId,
        LancerCompanyName,
        LancerCostScore,
        LancerEmail,
        LancerEvaluation,
        LancerIdNo,
        LancerIdType,
        LancerName,
        LancerSignBy,
        LancerPhone,
        LancerPlanScore,
        LancerProfessScore,
        LancerQualityScore,
        LancerResponsScore,
        LancerRoleTitle,
        LancerTotalScore,
        LancerTrueName,
        ModifyBy,
        ModifyOn,
        NeedDailyReport,
        Postform,
        ProcessStatus,
        ProcessStatusDesc,
        ProjectId,
        Status,
        Title,
        Version,
        WeeklyHours,
        ContractMilestone,
        ContractReport,
        ContractLog;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int ATTACHMENTLINK = AttributesEnum.AttachmentLink.index();
    public static final int CLIENTCOMPANYID = AttributesEnum.ClientCompanyId.index();
    public static final int CLIENTCOMPANYNAME = AttributesEnum.ClientCompanyName.index();
    public static final int CLIENTCONFIRMDELAYDAY = AttributesEnum.ClientConfirmDelayDay.index();
    public static final int CLIENTEMAIL = AttributesEnum.ClientEmail.index();
    public static final int CLIENTIDNO = AttributesEnum.ClientIdNo.index();
    public static final int CLIENTIDTYPE = AttributesEnum.ClientIdType.index();
    public static final int CLIENTNAME = AttributesEnum.ClientName.index();
    public static final int CLIENTSIGNBY = AttributesEnum.ClientSignBy.index();
    public static final int CLIENTPAYDELAYDAY = AttributesEnum.ClientPayDelayDay.index();
    public static final int CLIENTPHONE = AttributesEnum.ClientPhone.index();
    public static final int CLIENTROLETITLE = AttributesEnum.ClientRoleTitle.index();
    public static final int CLIENTTOTALSCORE = AttributesEnum.ClientTotalScore.index();
    public static final int CLIENTTRUENAME = AttributesEnum.ClientTrueName.index();
    public static final int CONTENT = AttributesEnum.Content.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int DATEEND = AttributesEnum.DateEnd.index();
    public static final int DATESTART = AttributesEnum.DateStart.index();
    public static final int FIXEDPAYDATE = AttributesEnum.FixedPayDate.index();
    public static final int FIXEDPAYDELAYHOLIDAY = AttributesEnum.FixedPayDelayHoliday.index();
    public static final int FIXEDPAYPRICE = AttributesEnum.FixedPayPrice.index();
    public static final int HOURLYPAY = AttributesEnum.HourlyPay.index();
    public static final int LANCERCOMPANYID = AttributesEnum.LancerCompanyId.index();
    public static final int LANCERCOMPANYNAME = AttributesEnum.LancerCompanyName.index();
    public static final int LANCERCOSTSCORE = AttributesEnum.LancerCostScore.index();
    public static final int LANCEREMAIL = AttributesEnum.LancerEmail.index();
    public static final int LANCEREVALUATION = AttributesEnum.LancerEvaluation.index();
    public static final int LANCERIDNO = AttributesEnum.LancerIdNo.index();
    public static final int LANCERIDTYPE = AttributesEnum.LancerIdType.index();
    public static final int LANCERNAME = AttributesEnum.LancerName.index();
    public static final int LANCERSIGNBY = AttributesEnum.LancerSignBy.index();
    public static final int LANCERPHONE = AttributesEnum.LancerPhone.index();
    public static final int LANCERPLANSCORE = AttributesEnum.LancerPlanScore.index();
    public static final int LANCERPROFESSSCORE = AttributesEnum.LancerProfessScore.index();
    public static final int LANCERQUALITYSCORE = AttributesEnum.LancerQualityScore.index();
    public static final int LANCERRESPONSSCORE = AttributesEnum.LancerResponsScore.index();
    public static final int LANCERROLETITLE = AttributesEnum.LancerRoleTitle.index();
    public static final int LANCERTOTALSCORE = AttributesEnum.LancerTotalScore.index();
    public static final int LANCERTRUENAME = AttributesEnum.LancerTrueName.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int NEEDDAILYREPORT = AttributesEnum.NeedDailyReport.index();
    public static final int POSTFORM = AttributesEnum.Postform.index();
    public static final int PROCESSSTATUS = AttributesEnum.ProcessStatus.index();
    public static final int PROCESSSTATUSDESC = AttributesEnum.ProcessStatusDesc.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int WEEKLYHOURS = AttributesEnum.WeeklyHours.index();
    public static final int CONTRACTMILESTONE = AttributesEnum.ContractMilestone.index();
    public static final int CONTRACTREPORT = AttributesEnum.ContractReport.index();
    public static final int CONTRACTLOG = AttributesEnum.ContractLog.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContractVORowImpl() {
    }

    /**
     * Gets ContractEO entity object.
     * @return the ContractEO
     */
    public ContractEOImpl getContractEO() {
        return (ContractEOImpl) getEntity(ENTITY_CONTRACTEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for CONTENT using the alias name Content.
     * @return the CONTENT
     */
    public ClobDomain getContent() {
        return (ClobDomain) getAttributeInternal(CONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTENT using the alias name Content.
     * @param value value to set the CONTENT
     */
    public void setContent(ClobDomain value) {
        setAttributeInternal(CONTENT, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT_LINK using the alias name AttachmentLink.
     * @return the ATTACHMENT_LINK
     */
    public String getAttachmentLink() {
        return (String) getAttributeInternal(ATTACHMENTLINK);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT_LINK using the alias name AttachmentLink.
     * @param value value to set the ATTACHMENT_LINK
     */
    public void setAttachmentLink(String value) {
        setAttributeInternal(ATTACHMENTLINK, value);
    }

    /**
     * Gets the attribute value for CLIENT_COMPANY_ID using the alias name ClientCompanyId.
     * @return the CLIENT_COMPANY_ID
     */
    public String getClientCompanyId() {
        return (String) getAttributeInternal(CLIENTCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_COMPANY_ID using the alias name ClientCompanyId.
     * @param value value to set the CLIENT_COMPANY_ID
     */
    public void setClientCompanyId(String value) {
        setAttributeInternal(CLIENTCOMPANYID, value);
    }

    /**
     * Gets the attribute value for CLIENT_COMPANY_NAME using the alias name ClientCompanyName.
     * @return the CLIENT_COMPANY_NAME
     */
    public String getClientCompanyName() {
        return (String) getAttributeInternal(CLIENTCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_COMPANY_NAME using the alias name ClientCompanyName.
     * @param value value to set the CLIENT_COMPANY_NAME
     */
    public void setClientCompanyName(String value) {
        setAttributeInternal(CLIENTCOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for CLIENT_NAME using the alias name ClientName.
     * @return the CLIENT_NAME
     */
    public String getClientName() {
        return (String) getAttributeInternal(CLIENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_NAME using the alias name ClientName.
     * @param value value to set the CLIENT_NAME
     */
    public void setClientName(String value) {
        setAttributeInternal(CLIENTNAME, value);
    }

    /**
     * Gets the attribute value for CLIENT_SIGN_BY using the alias name ClientSignBy.
     * @return the CLIENT_SIGN_BY
     */
    public String getClientSignBy() {
        return (String) getAttributeInternal(CLIENTSIGNBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_SIGN_BY using the alias name ClientSignBy.
     * @param value value to set the CLIENT_SIGN_BY
     */
    public void setClientSignBy(String value) {
        setAttributeInternal(CLIENTSIGNBY, value);
    }

    /**
     * Gets the attribute value for LANCER_NAME using the alias name LancerName.
     * @return the LANCER_NAME
     */
    public String getLancerName() {
        return (String) getAttributeInternal(LANCERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_NAME using the alias name LancerName.
     * @param value value to set the LANCER_NAME
     */
    public void setLancerName(String value) {
        setAttributeInternal(LANCERNAME, value);
    }

    /**
     * Gets the attribute value for LANCER_SIGN_BY using the alias name LancerSignBy.
     * @return the LANCER_SIGN_BY
     */
    public String getLancerSignBy() {
        return (String) getAttributeInternal(LANCERSIGNBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_SIGN_BY using the alias name LancerSignBy.
     * @param value value to set the LANCER_SIGN_BY
     */
    public void setLancerSignBy(String value) {
        setAttributeInternal(LANCERSIGNBY, value);
    }

    /**
     * Gets the attribute value for LANCER_PHONE using the alias name LancerPhone.
     * @return the LANCER_PHONE
     */
    public String getLancerPhone() {
        return (String) getAttributeInternal(LANCERPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_PHONE using the alias name LancerPhone.
     * @param value value to set the LANCER_PHONE
     */
    public void setLancerPhone(String value) {
        setAttributeInternal(LANCERPHONE, value);
    }

    /**
     * Gets the attribute value for DATE_START using the alias name DateStart.
     * @return the DATE_START
     */
    public Date getDateStart() {
        return (Date) getAttributeInternal(DATESTART);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_START using the alias name DateStart.
     * @param value value to set the DATE_START
     */
    public void setDateStart(Date value) {
        setAttributeInternal(DATESTART, value);
    }

    /**
     * Gets the attribute value for DATE_END using the alias name DateEnd.
     * @return the DATE_END
     */
    public Date getDateEnd() {
        return (Date) getAttributeInternal(DATEEND);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_END using the alias name DateEnd.
     * @param value value to set the DATE_END
     */
    public void setDateEnd(Date value) {
        setAttributeInternal(DATEEND, value);
    }

    /**
     * Gets the attribute value for CLIENT_ROLE_TITLE using the alias name ClientRoleTitle.
     * @return the CLIENT_ROLE_TITLE
     */
    public String getClientRoleTitle() {
        return (String) getAttributeInternal(CLIENTROLETITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_ROLE_TITLE using the alias name ClientRoleTitle.
     * @param value value to set the CLIENT_ROLE_TITLE
     */
    public void setClientRoleTitle(String value) {
        setAttributeInternal(CLIENTROLETITLE, value);
    }

    /**
     * Gets the attribute value for LANCER_ROLE_TITLE using the alias name LancerRoleTitle.
     * @return the LANCER_ROLE_TITLE
     */
    public String getLancerRoleTitle() {
        return (String) getAttributeInternal(LANCERROLETITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_ROLE_TITLE using the alias name LancerRoleTitle.
     * @param value value to set the LANCER_ROLE_TITLE
     */
    public void setLancerRoleTitle(String value) {
        setAttributeInternal(LANCERROLETITLE, value);
    }

    /**
     * Gets the attribute value for POSTFORM using the alias name Postform.
     * @return the POSTFORM
     */
    public String getPostform() {
        return (String) getAttributeInternal(POSTFORM);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTFORM using the alias name Postform.
     * @param value value to set the POSTFORM
     */
    public void setPostform(String value) {
        setAttributeInternal(POSTFORM, value);
    }

    /**
     * Gets the attribute value for HOURLY_PAY using the alias name HourlyPay.
     * @return the HOURLY_PAY
     */
    public BigDecimal getHourlyPay() {
        return (BigDecimal) getAttributeInternal(HOURLYPAY);
    }

    /**
     * Sets <code>value</code> as attribute value for HOURLY_PAY using the alias name HourlyPay.
     * @param value value to set the HOURLY_PAY
     */
    public void setHourlyPay(BigDecimal value) {
        setAttributeInternal(HOURLYPAY, value);
    }

    /**
     * Gets the attribute value for LANCER_COMPANY_ID using the alias name LancerCompanyId.
     * @return the LANCER_COMPANY_ID
     */
    public String getLancerCompanyId() {
        return (String) getAttributeInternal(LANCERCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_COMPANY_ID using the alias name LancerCompanyId.
     * @param value value to set the LANCER_COMPANY_ID
     */
    public void setLancerCompanyId(String value) {
        setAttributeInternal(LANCERCOMPANYID, value);
    }

    /**
     * Gets the attribute value for LANCER_COMPANY_NAME using the alias name LancerCompanyName.
     * @return the LANCER_COMPANY_NAME
     */
    public String getLancerCompanyName() {
        return (String) getAttributeInternal(LANCERCOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_COMPANY_NAME using the alias name LancerCompanyName.
     * @param value value to set the LANCER_COMPANY_NAME
     */
    public void setLancerCompanyName(String value) {
        setAttributeInternal(LANCERCOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for WEEKLY_HOURS using the alias name WeeklyHours.
     * @return the WEEKLY_HOURS
     */
    public Integer getWeeklyHours() {
        return (Integer) getAttributeInternal(WEEKLYHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEKLY_HOURS using the alias name WeeklyHours.
     * @param value value to set the WEEKLY_HOURS
     */
    public void setWeeklyHours(Integer value) {
        setAttributeInternal(WEEKLYHOURS, value);
    }

    /**
     * Gets the attribute value for FIXED_PAY_PRICE using the alias name FixedPayPrice.
     * @return the FIXED_PAY_PRICE
     */
    public BigDecimal getFixedPayPrice() {
        return (BigDecimal) getAttributeInternal(FIXEDPAYPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for FIXED_PAY_PRICE using the alias name FixedPayPrice.
     * @param value value to set the FIXED_PAY_PRICE
     */
    public void setFixedPayPrice(BigDecimal value) {
        setAttributeInternal(FIXEDPAYPRICE, value);
    }

    /**
     * Gets the attribute value for CLIENT_CONFIRM_DELAY_DAY using the alias name ClientConfirmDelayDay.
     * @return the CLIENT_CONFIRM_DELAY_DAY
     */
    public Integer getClientConfirmDelayDay() {
        return (Integer) getAttributeInternal(CLIENTCONFIRMDELAYDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_CONFIRM_DELAY_DAY using the alias name ClientConfirmDelayDay.
     * @param value value to set the CLIENT_CONFIRM_DELAY_DAY
     */
    public void setClientConfirmDelayDay(Integer value) {
        setAttributeInternal(CLIENTCONFIRMDELAYDAY, value);
    }

    /**
     * Gets the attribute value for CLIENT_EMAIL using the alias name ClientEmail.
     * @return the CLIENT_EMAIL
     */
    public String getClientEmail() {
        return (String) getAttributeInternal(CLIENTEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_EMAIL using the alias name ClientEmail.
     * @param value value to set the CLIENT_EMAIL
     */
    public void setClientEmail(String value) {
        setAttributeInternal(CLIENTEMAIL, value);
    }

    /**
     * Gets the attribute value for CLIENT_ID_NO using the alias name ClientIdNo.
     * @return the CLIENT_ID_NO
     */
    public String getClientIdNo() {
        return (String) getAttributeInternal(CLIENTIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_ID_NO using the alias name ClientIdNo.
     * @param value value to set the CLIENT_ID_NO
     */
    public void setClientIdNo(String value) {
        setAttributeInternal(CLIENTIDNO, value);
    }

    /**
     * Gets the attribute value for CLIENT_ID_TYPE using the alias name ClientIdType.
     * @return the CLIENT_ID_TYPE
     */
    public String getClientIdType() {
        return (String) getAttributeInternal(CLIENTIDTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_ID_TYPE using the alias name ClientIdType.
     * @param value value to set the CLIENT_ID_TYPE
     */
    public void setClientIdType(String value) {
        setAttributeInternal(CLIENTIDTYPE, value);
    }

    /**
     * Gets the attribute value for CLIENT_PAY_DELAY_DAY using the alias name ClientPayDelayDay.
     * @return the CLIENT_PAY_DELAY_DAY
     */
    public Integer getClientPayDelayDay() {
        return (Integer) getAttributeInternal(CLIENTPAYDELAYDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_PAY_DELAY_DAY using the alias name ClientPayDelayDay.
     * @param value value to set the CLIENT_PAY_DELAY_DAY
     */
    public void setClientPayDelayDay(Integer value) {
        setAttributeInternal(CLIENTPAYDELAYDAY, value);
    }

    /**
     * Gets the attribute value for CLIENT_PHONE using the alias name ClientPhone.
     * @return the CLIENT_PHONE
     */
    public String getClientPhone() {
        return (String) getAttributeInternal(CLIENTPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_PHONE using the alias name ClientPhone.
     * @param value value to set the CLIENT_PHONE
     */
    public void setClientPhone(String value) {
        setAttributeInternal(CLIENTPHONE, value);
    }

    /**
     * Gets the attribute value for FIXED_PAY_DATE using the alias name FixedPayDate.
     * @return the FIXED_PAY_DATE
     */
    public Integer getFixedPayDate() {
        return (Integer) getAttributeInternal(FIXEDPAYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FIXED_PAY_DATE using the alias name FixedPayDate.
     * @param value value to set the FIXED_PAY_DATE
     */
    public void setFixedPayDate(Integer value) {
        setAttributeInternal(FIXEDPAYDATE, value);
    }

    /**
     * Gets the attribute value for FIXED_PAY_DELAY_HOLIDAY using the alias name FixedPayDelayHoliday.
     * @return the FIXED_PAY_DELAY_HOLIDAY
     */
    public String getFixedPayDelayHoliday() {
        return (String) getAttributeInternal(FIXEDPAYDELAYHOLIDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for FIXED_PAY_DELAY_HOLIDAY using the alias name FixedPayDelayHoliday.
     * @param value value to set the FIXED_PAY_DELAY_HOLIDAY
     */
    public void setFixedPayDelayHoliday(String value) {
        setAttributeInternal(FIXEDPAYDELAYHOLIDAY, value);
    }

    /**
     * Gets the attribute value for NEED_DAILY_REPORT using the alias name NeedDailyReport.
     * @return the NEED_DAILY_REPORT
     */
    public String getNeedDailyReport() {
        return (String) getAttributeInternal(NEEDDAILYREPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for NEED_DAILY_REPORT using the alias name NeedDailyReport.
     * @param value value to set the NEED_DAILY_REPORT
     */
    public void setNeedDailyReport(String value) {
        setAttributeInternal(NEEDDAILYREPORT, value);
    }

    /**
     * Gets the attribute value for PROCESS_STATUS using the alias name ProcessStatus.
     * @return the PROCESS_STATUS
     */
    public String getProcessStatus() {
        return (String) getAttributeInternal(PROCESSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_STATUS using the alias name ProcessStatus.
     * @param value value to set the PROCESS_STATUS
     */
    public void setProcessStatus(String value) {
        setAttributeInternal(PROCESSSTATUS, value);
    }

    /**
     * Gets the attribute value for PROCESS_STATUS_DESC using the alias name ProcessStatusDesc.
     * @return the PROCESS_STATUS_DESC
     */
    public String getProcessStatusDesc() {
        return (String) getAttributeInternal(PROCESSSTATUSDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_STATUS_DESC using the alias name ProcessStatusDesc.
     * @param value value to set the PROCESS_STATUS_DESC
     */
    public void setProcessStatusDesc(String value) {
        setAttributeInternal(PROCESSSTATUSDESC, value);
    }

    /**
     * Gets the attribute value for LANCER_TOTAL_SCORE using the alias name LancerTotalScore.
     * @return the LANCER_TOTAL_SCORE
     */
    public BigDecimal getLancerTotalScore() {
        return (BigDecimal) getAttributeInternal(LANCERTOTALSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_TOTAL_SCORE using the alias name LancerTotalScore.
     * @param value value to set the LANCER_TOTAL_SCORE
     */
    public void setLancerTotalScore(BigDecimal value) {
        setAttributeInternal(LANCERTOTALSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_TRUE_NAME using the alias name LancerTrueName.
     * @return the LANCER_TRUE_NAME
     */
    public String getLancerTrueName() {
        return (String) getAttributeInternal(LANCERTRUENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_TRUE_NAME using the alias name LancerTrueName.
     * @param value value to set the LANCER_TRUE_NAME
     */
    public void setLancerTrueName(String value) {
        setAttributeInternal(LANCERTRUENAME, value);
    }

    /**
     * Gets the attribute value for LANCER_QUALITY_SCORE using the alias name LancerQualityScore.
     * @return the LANCER_QUALITY_SCORE
     */
    public BigDecimal getLancerQualityScore() {
        return (BigDecimal) getAttributeInternal(LANCERQUALITYSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_QUALITY_SCORE using the alias name LancerQualityScore.
     * @param value value to set the LANCER_QUALITY_SCORE
     */
    public void setLancerQualityScore(BigDecimal value) {
        setAttributeInternal(LANCERQUALITYSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_PROFESS_SCORE using the alias name LancerProfessScore.
     * @return the LANCER_PROFESS_SCORE
     */
    public BigDecimal getLancerProfessScore() {
        return (BigDecimal) getAttributeInternal(LANCERPROFESSSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_PROFESS_SCORE using the alias name LancerProfessScore.
     * @param value value to set the LANCER_PROFESS_SCORE
     */
    public void setLancerProfessScore(BigDecimal value) {
        setAttributeInternal(LANCERPROFESSSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_COST_SCORE using the alias name LancerCostScore.
     * @return the LANCER_COST_SCORE
     */
    public BigDecimal getLancerCostScore() {
        return (BigDecimal) getAttributeInternal(LANCERCOSTSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_COST_SCORE using the alias name LancerCostScore.
     * @param value value to set the LANCER_COST_SCORE
     */
    public void setLancerCostScore(BigDecimal value) {
        setAttributeInternal(LANCERCOSTSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_EMAIL using the alias name LancerEmail.
     * @return the LANCER_EMAIL
     */
    public String getLancerEmail() {
        return (String) getAttributeInternal(LANCEREMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_EMAIL using the alias name LancerEmail.
     * @param value value to set the LANCER_EMAIL
     */
    public void setLancerEmail(String value) {
        setAttributeInternal(LANCEREMAIL, value);
    }

    /**
     * Gets the attribute value for LANCER_PLAN_SCORE using the alias name LancerPlanScore.
     * @return the LANCER_PLAN_SCORE
     */
    public BigDecimal getLancerPlanScore() {
        return (BigDecimal) getAttributeInternal(LANCERPLANSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_PLAN_SCORE using the alias name LancerPlanScore.
     * @param value value to set the LANCER_PLAN_SCORE
     */
    public void setLancerPlanScore(BigDecimal value) {
        setAttributeInternal(LANCERPLANSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_RESPONS_SCORE using the alias name LancerResponsScore.
     * @return the LANCER_RESPONS_SCORE
     */
    public BigDecimal getLancerResponsScore() {
        return (BigDecimal) getAttributeInternal(LANCERRESPONSSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_RESPONS_SCORE using the alias name LancerResponsScore.
     * @param value value to set the LANCER_RESPONS_SCORE
     */
    public void setLancerResponsScore(BigDecimal value) {
        setAttributeInternal(LANCERRESPONSSCORE, value);
    }

    /**
     * Gets the attribute value for LANCER_EVALUATION using the alias name LancerEvaluation.
     * @return the LANCER_EVALUATION
     */
    public String getLancerEvaluation() {
        return (String) getAttributeInternal(LANCEREVALUATION);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_EVALUATION using the alias name LancerEvaluation.
     * @param value value to set the LANCER_EVALUATION
     */
    public void setLancerEvaluation(String value) {
        setAttributeInternal(LANCEREVALUATION, value);
    }

    /**
     * Gets the attribute value for LANCER_ID_NO using the alias name LancerIdNo.
     * @return the LANCER_ID_NO
     */
    public String getLancerIdNo() {
        return (String) getAttributeInternal(LANCERIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_ID_NO using the alias name LancerIdNo.
     * @param value value to set the LANCER_ID_NO
     */
    public void setLancerIdNo(String value) {
        setAttributeInternal(LANCERIDNO, value);
    }

    /**
     * Gets the attribute value for LANCER_ID_TYPE using the alias name LancerIdType.
     * @return the LANCER_ID_TYPE
     */
    public String getLancerIdType() {
        return (String) getAttributeInternal(LANCERIDTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_ID_TYPE using the alias name LancerIdType.
     * @param value value to set the LANCER_ID_TYPE
     */
    public void setLancerIdType(String value) {
        setAttributeInternal(LANCERIDTYPE, value);
    }

    /**
     * Gets the attribute value for CLIENT_TOTAL_SCORE using the alias name ClientTotalScore.
     * @return the CLIENT_TOTAL_SCORE
     */
    public String getClientTotalScore() {
        return (String) getAttributeInternal(CLIENTTOTALSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_TOTAL_SCORE using the alias name ClientTotalScore.
     * @param value value to set the CLIENT_TOTAL_SCORE
     */
    public void setClientTotalScore(String value) {
        setAttributeInternal(CLIENTTOTALSCORE, value);
    }

    /**
     * Gets the attribute value for CLIENT_TRUE_NAME using the alias name ClientTrueName.
     * @return the CLIENT_TRUE_NAME
     */
    public String getClientTrueName() {
        return (String) getAttributeInternal(CLIENTTRUENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CLIENT_TRUE_NAME using the alias name ClientTrueName.
     * @param value value to set the CLIENT_TRUE_NAME
     */
    public void setClientTrueName(String value) {
        setAttributeInternal(CLIENTTRUENAME, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractMilestone.
     */
    public RowIterator getContractMilestone() {
        return (RowIterator) getAttributeInternal(CONTRACTMILESTONE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractReport.
     */
    public RowIterator getContractReport() {
        return (RowIterator) getAttributeInternal(CONTRACTREPORT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractLog.
     */
    public RowIterator getContractLog() {
        return (RowIterator) getAttributeInternal(CONTRACTLOG);
    }
}

