package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 13 16:36:34 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractReportVORowImpl extends BaseViewRowImpl {


    public static final int ENTITY_CONTRACTREPORTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        ProjectId,
        ContractId,
        DateRecord,
        WorkContent,
        WorkHours,
        WorkRemark,
        Status,
        StatusRemark,
        PayBillNumber;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int DATERECORD = AttributesEnum.DateRecord.index();
    public static final int WORKCONTENT = AttributesEnum.WorkContent.index();
    public static final int WORKHOURS = AttributesEnum.WorkHours.index();
    public static final int WORKREMARK = AttributesEnum.WorkRemark.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STATUSREMARK = AttributesEnum.StatusRemark.index();
    public static final int PAYBILLNUMBER = AttributesEnum.PayBillNumber.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContractReportVORowImpl() {
    }

    /**
     * Gets ContractReportEO entity object.
     * @return the ContractReportEO
     */
    public BaseEntityImpl getContractReportEO() {
        return (BaseEntityImpl) getEntity(ENTITY_CONTRACTREPORTEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public String getProjectId() {
        return (String) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(String value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public String getContractId() {
        return (String) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(String value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for DATE_RECORD using the alias name DateRecord.
     * @return the DATE_RECORD
     */
    public Timestamp getDateRecord() {
        return (Timestamp) getAttributeInternal(DATERECORD);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_RECORD using the alias name DateRecord.
     * @param value value to set the DATE_RECORD
     */
    public void setDateRecord(Timestamp value) {
        setAttributeInternal(DATERECORD, value);
    }

    /**
     * Gets the attribute value for WORK_CONTENT using the alias name WorkContent.
     * @return the WORK_CONTENT
     */
    public ClobDomain getWorkContent() {
        return (ClobDomain) getAttributeInternal(WORKCONTENT);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_CONTENT using the alias name WorkContent.
     * @param value value to set the WORK_CONTENT
     */
    public void setWorkContent(ClobDomain value) {
        setAttributeInternal(WORKCONTENT, value);
    }

    /**
     * Gets the attribute value for WORK_HOURS using the alias name WorkHours.
     * @return the WORK_HOURS
     */
    public BigDecimal getWorkHours() {
        return (BigDecimal) getAttributeInternal(WORKHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_HOURS using the alias name WorkHours.
     * @param value value to set the WORK_HOURS
     */
    public void setWorkHours(BigDecimal value) {
        setAttributeInternal(WORKHOURS, value);
    }

    /**
     * Gets the attribute value for WORK_REMARK using the alias name WorkRemark.
     * @return the WORK_REMARK
     */
    public String getWorkRemark() {
        return (String) getAttributeInternal(WORKREMARK);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_REMARK using the alias name WorkRemark.
     * @param value value to set the WORK_REMARK
     */
    public void setWorkRemark(String value) {
        setAttributeInternal(WORKREMARK, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for STATUS_REMARK using the alias name StatusRemark.
     * @return the STATUS_REMARK
     */
    public String getStatusRemark() {
        return (String) getAttributeInternal(STATUSREMARK);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS_REMARK using the alias name StatusRemark.
     * @param value value to set the STATUS_REMARK
     */
    public void setStatusRemark(String value) {
        setAttributeInternal(STATUSREMARK, value);
    }

    /**
     * Gets the attribute value for PAY_BILL_NUMBER using the alias name PayBillNumber.
     * @return the PAY_BILL_NUMBER
     */
    public String getPayBillNumber() {
        return (String) getAttributeInternal(PAYBILLNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_BILL_NUMBER using the alias name PayBillNumber.
     * @param value value to set the PAY_BILL_NUMBER
     */
    public void setPayBillNumber(String value) {
        setAttributeInternal(PAYBILLNUMBER, value);
    }
}

