package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 13 16:36:16 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FinUserAccountLogVORowImpl extends BaseViewRowImpl {

    public static final int ENTITY_FINUSERACCOUNTLOGEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        MoveTarget,
        MoveDirection,
        MoveAmount,
        OtherFee,
        AfterAccountAmount,
        BeforeAccountAmount,
        Description,
        Success,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int MOVETARGET = AttributesEnum.MoveTarget.index();
    public static final int MOVEDIRECTION = AttributesEnum.MoveDirection.index();
    public static final int MOVEAMOUNT = AttributesEnum.MoveAmount.index();
    public static final int OTHERFEE = AttributesEnum.OtherFee.index();
    public static final int AFTERACCOUNTAMOUNT = AttributesEnum.AfterAccountAmount.index();
    public static final int BEFOREACCOUNTAMOUNT = AttributesEnum.BeforeAccountAmount.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SUCCESS = AttributesEnum.Success.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FinUserAccountLogVORowImpl() {
    }

    /**
     * Gets FinUserAccountLogEO entity object.
     * @return the FinUserAccountLogEO
     */
    public BaseEntityImpl getFinUserAccountLogEO() {
        return (BaseEntityImpl) getEntity(ENTITY_FINUSERACCOUNTLOGEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for MOVE_TARGET using the alias name MoveTarget.
     * @return the MOVE_TARGET
     */
    public String getMoveTarget() {
        return (String) getAttributeInternal(MOVETARGET);
    }

    /**
     * Sets <code>value</code> as attribute value for MOVE_TARGET using the alias name MoveTarget.
     * @param value value to set the MOVE_TARGET
     */
    public void setMoveTarget(String value) {
        setAttributeInternal(MOVETARGET, value);
    }

    /**
     * Gets the attribute value for MOVE_DIRECTION using the alias name MoveDirection.
     * @return the MOVE_DIRECTION
     */
    public String getMoveDirection() {
        return (String) getAttributeInternal(MOVEDIRECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for MOVE_DIRECTION using the alias name MoveDirection.
     * @param value value to set the MOVE_DIRECTION
     */
    public void setMoveDirection(String value) {
        setAttributeInternal(MOVEDIRECTION, value);
    }

    /**
     * Gets the attribute value for MOVE_AMOUNT using the alias name MoveAmount.
     * @return the MOVE_AMOUNT
     */
    public BigDecimal getMoveAmount() {
        return (BigDecimal) getAttributeInternal(MOVEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for MOVE_AMOUNT using the alias name MoveAmount.
     * @param value value to set the MOVE_AMOUNT
     */
    public void setMoveAmount(BigDecimal value) {
        setAttributeInternal(MOVEAMOUNT, value);
    }

    /**
     * Gets the attribute value for OTHER_FEE using the alias name OtherFee.
     * @return the OTHER_FEE
     */
    public BigDecimal getOtherFee() {
        return (BigDecimal) getAttributeInternal(OTHERFEE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_FEE using the alias name OtherFee.
     * @param value value to set the OTHER_FEE
     */
    public void setOtherFee(BigDecimal value) {
        setAttributeInternal(OTHERFEE, value);
    }

    /**
     * Gets the attribute value for AFTER_ACCOUNT_AMOUNT using the alias name AfterAccountAmount.
     * @return the AFTER_ACCOUNT_AMOUNT
     */
    public BigDecimal getAfterAccountAmount() {
        return (BigDecimal) getAttributeInternal(AFTERACCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AFTER_ACCOUNT_AMOUNT using the alias name AfterAccountAmount.
     * @param value value to set the AFTER_ACCOUNT_AMOUNT
     */
    public void setAfterAccountAmount(BigDecimal value) {
        setAttributeInternal(AFTERACCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for BEFORE_ACCOUNT_AMOUNT using the alias name BeforeAccountAmount.
     * @return the BEFORE_ACCOUNT_AMOUNT
     */
    public BigDecimal getBeforeAccountAmount() {
        return (BigDecimal) getAttributeInternal(BEFOREACCOUNTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for BEFORE_ACCOUNT_AMOUNT using the alias name BeforeAccountAmount.
     * @param value value to set the BEFORE_ACCOUNT_AMOUNT
     */
    public void setBeforeAccountAmount(BigDecimal value) {
        setAttributeInternal(BEFOREACCOUNTAMOUNT, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SUCCESS using the alias name Success.
     * @return the SUCCESS
     */
    public String getSuccess() {
        return (String) getAttributeInternal(SUCCESS);
    }

    /**
     * Sets <code>value</code> as attribute value for SUCCESS using the alias name Success.
     * @param value value to set the SUCCESS
     */
    public void setSuccess(String value) {
        setAttributeInternal(SUCCESS, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Timestamp value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_BY using the alias name ModifyBy.
     * @param value value to set the MODIFY_BY
     */
    public void setModifyBy(String value) {
        setAttributeInternal(MODIFYBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_ON using the alias name ModifyOn.
     * @param value value to set the MODIFY_ON
     */
    public void setModifyOn(Timestamp value) {
        setAttributeInternal(MODIFYON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }
}

