package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 13 16:36:21 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FinUserAccountVORowImpl extends BaseViewRowImpl {

    public static final int ENTITY_FINUSERACCOUNTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserName,
        AvaliableAmount,
        FreezeAmount,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version,
        FinPayBill,
        FinPayBill1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int AVALIABLEAMOUNT = AttributesEnum.AvaliableAmount.index();
    public static final int FREEZEAMOUNT = AttributesEnum.FreezeAmount.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int FINPAYBILL = AttributesEnum.FinPayBill.index();
    public static final int FINPAYBILL1 = AttributesEnum.FinPayBill1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FinUserAccountVORowImpl() {
    }

    /**
     * Gets FinUserAccountEO entity object.
     * @return the FinUserAccountEO
     */
    public BaseEntityImpl getFinUserAccountEO() {
        return (BaseEntityImpl) getEntity(ENTITY_FINUSERACCOUNTEO);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for AVALIABLE_AMOUNT using the alias name AvaliableAmount.
     * @return the AVALIABLE_AMOUNT
     */
    public BigDecimal getAvaliableAmount() {
        return (BigDecimal) getAttributeInternal(AVALIABLEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AVALIABLE_AMOUNT using the alias name AvaliableAmount.
     * @param value value to set the AVALIABLE_AMOUNT
     */
    public void setAvaliableAmount(BigDecimal value) {
        setAttributeInternal(AVALIABLEAMOUNT, value);
    }

    /**
     * Gets the attribute value for FREEZE_AMOUNT using the alias name FreezeAmount.
     * @return the FREEZE_AMOUNT
     */
    public BigDecimal getFreezeAmount() {
        return (BigDecimal) getAttributeInternal(FREEZEAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FREEZE_AMOUNT using the alias name FreezeAmount.
     * @param value value to set the FREEZE_AMOUNT
     */
    public void setFreezeAmount(BigDecimal value) {
        setAttributeInternal(FREEZEAMOUNT, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Timestamp value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_BY using the alias name ModifyBy.
     * @param value value to set the MODIFY_BY
     */
    public void setModifyBy(String value) {
        setAttributeInternal(MODIFYBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_ON using the alias name ModifyOn.
     * @param value value to set the MODIFY_ON
     */
    public void setModifyOn(Timestamp value) {
        setAttributeInternal(MODIFYON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FinPayBill.
     */
    public RowIterator getFinPayBill() {
        return (RowIterator) getAttributeInternal(FINPAYBILL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FinPayBill1.
     */
    public RowIterator getFinPayBill1() {
        return (RowIterator) getAttributeInternal(FINPAYBILL1);
    }
}

