package com.lance.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 12 09:54:16 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobCategoryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public JobCategoryVOImpl() {
    }
}

