package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 23:14:02 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobTemplateVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public JobTemplateVOImpl() {
    }

    /**
     * Returns the variable value for pCreateBy.
     * @return variable value for pCreateBy
     */
    public String getpCreateBy() {
        return (String) ensureVariableManager().getVariableValue("pCreateBy");
    }

    /**
     * Sets <code>value</code> for variable pCreateBy.
     * @param value value to bind as pCreateBy
     */
    public void setpCreateBy(String value) {
        ensureVariableManager().setVariableValue("pCreateBy", value);
    }

    /**
     * Returns the variable value for pJobCategoryId.
     * @return variable value for pJobCategoryId
     */
    public String getpJobCategoryId() {
        return (String) ensureVariableManager().getVariableValue("pJobCategoryId");
    }

    /**
     * Sets <code>value</code> for variable pJobCategoryId.
     * @param value value to bind as pJobCategoryId
     */
    public void setpJobCategoryId(String value) {
        ensureVariableManager().setVariableValue("pJobCategoryId", value);
    }
}

