package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import oracle.jbo.JboException;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 23:14:02 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobTemplateVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_JOBTEMPLATEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        JobCategoryId,
        NameEn,
        NameCn,
        DescriptionCn,
        DescriptionEn,
        Tips,
        Type,
        DescriptionCnTxt,
        DescriptionEnTxt,
        JobTemplateTypeVVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int JOBCATEGORYID = AttributesEnum.JobCategoryId.index();
    public static final int NAMEEN = AttributesEnum.NameEn.index();
    public static final int NAMECN = AttributesEnum.NameCn.index();
    public static final int DESCRIPTIONCN = AttributesEnum.DescriptionCn.index();
    public static final int DESCRIPTIONEN = AttributesEnum.DescriptionEn.index();
    public static final int TIPS = AttributesEnum.Tips.index();
    public static final int TYPE = AttributesEnum.Type.index();
    public static final int DESCRIPTIONCNTXT = AttributesEnum.DescriptionCnTxt.index();
    public static final int DESCRIPTIONENTXT = AttributesEnum.DescriptionEnTxt.index();
    public static final int JOBTEMPLATETYPEVVO1 = AttributesEnum.JobTemplateTypeVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public JobTemplateVORowImpl() {
    }

    /**
     * Gets JobTemplateEO entity object.
     * @return the JobTemplateEO
     */
    public BaseEntityImpl getJobTemplateEO() {
        return (BaseEntityImpl) getEntity(ENTITY_JOBTEMPLATEEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for JOB_CATEGORY_ID using the alias name JobCategoryId.
     * @return the JOB_CATEGORY_ID
     */
    public String getJobCategoryId() {
        return (String) getAttributeInternal(JOBCATEGORYID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_CATEGORY_ID using the alias name JobCategoryId.
     * @param value value to set the JOB_CATEGORY_ID
     */
    public void setJobCategoryId(String value) {
        setAttributeInternal(JOBCATEGORYID, value);
    }

    /**
     * Gets the attribute value for NAME_EN using the alias name NameEn.
     * @return the NAME_EN
     */
    public String getNameEn() {
        return (String) getAttributeInternal(NAMEEN);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_EN using the alias name NameEn.
     * @param value value to set the NAME_EN
     */
    public void setNameEn(String value) {
        setAttributeInternal(NAMEEN, value);
    }

    /**
     * Gets the attribute value for NAME_CN using the alias name NameCn.
     * @return the NAME_CN
     */
    public String getNameCn() {
        return (String) getAttributeInternal(NAMECN);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_CN using the alias name NameCn.
     * @param value value to set the NAME_CN
     */
    public void setNameCn(String value) {
        setAttributeInternal(NAMECN, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION_CN using the alias name DescriptionCn.
     * @return the DESCRIPTION_CN
     */
    public ClobDomain getDescriptionCn() {
        return (ClobDomain) getAttributeInternal(DESCRIPTIONCN);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION_CN using the alias name DescriptionCn.
     * @param value value to set the DESCRIPTION_CN
     */
    public void setDescriptionCn(ClobDomain value) {
        setAttributeInternal(DESCRIPTIONCN, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION_EN using the alias name DescriptionEn.
     * @return the DESCRIPTION_EN
     */
    public ClobDomain getDescriptionEn() {
        return (ClobDomain) getAttributeInternal(DESCRIPTIONEN);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION_EN using the alias name DescriptionEn.
     * @param value value to set the DESCRIPTION_EN
     */
    public void setDescriptionEn(ClobDomain value) {
        setAttributeInternal(DESCRIPTIONEN, value);
    }

    /**
     * Gets the attribute value for TIPS using the alias name Tips.
     * @return the TIPS
     */
    public String getTips() {
        return (String) getAttributeInternal(TIPS);
    }

    /**
     * Sets <code>value</code> as attribute value for TIPS using the alias name Tips.
     * @param value value to set the TIPS
     */
    public void setTips(String value) {
        setAttributeInternal(TIPS, value);
    }

    /**
     * Gets the attribute value for TYPE using the alias name Type.
     * @return the TYPE
     */
    public Integer getType() {
        return (Integer) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE using the alias name Type.
     * @param value value to set the TYPE
     */
    public void setType(Integer value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescriptionCnTxt.
     * @return the DescriptionCnTxt
     */
    public String getDescriptionCnTxt() {
        ClobDomain c = this.getDescriptionCn();
        if (c != null)
            return c.toString();
        return (String) getAttributeInternal(DESCRIPTIONCNTXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescriptionCnTxt.
     * @param value value to set the  DescriptionCnTxt
     */
    public void setDescriptionCnTxt(String value) {
        ClobDomain c = new ClobDomain(value);
        this.setDescriptionCn(c);
        setAttributeInternal(DESCRIPTIONCNTXT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DescriptionEnTxt.
     * @return the DescriptionEnTxt
     */
    public String getDescriptionEnTxt() {
        ClobDomain c = this.getDescriptionEn();
        if (c != null)
            return c.toString();
        return (String) getAttributeInternal(DESCRIPTIONENTXT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DescriptionEnTxt.
     * @param value value to set the  DescriptionEnTxt
     */
    public void setDescriptionEnTxt(String value) {
        ClobDomain c = new ClobDomain(value);
        this.setDescriptionEn(c);
        setAttributeInternal(DESCRIPTIONENTXT, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> JobTemplateTypeVVO1.
     */
    public RowSet getJobTemplateTypeVVO1() {
        return (RowSet) getAttributeInternal(JOBTEMPLATETYPEVVO1);
    }
}

