package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 05 15:19:45 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LancerLocationListVORowImpl extends BaseViewRowImpl {


    public static final int ENTITY_LANCERLOCATIONLISTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        AreaId,
        CityId,
        CountryId,
        CurrentIn,
        FaxNumber,
        LancerId,
        ProvinceId,
        RegionId,
        Telphone,
        ZipCode,
        DetailLoc,
        LanceExp;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int AREAID = AttributesEnum.AreaId.index();
    public static final int CITYID = AttributesEnum.CityId.index();
    public static final int COUNTRYID = AttributesEnum.CountryId.index();
    public static final int CURRENTIN = AttributesEnum.CurrentIn.index();
    public static final int FAXNUMBER = AttributesEnum.FaxNumber.index();
    public static final int LANCERID = AttributesEnum.LancerId.index();
    public static final int PROVINCEID = AttributesEnum.ProvinceId.index();
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int TELPHONE = AttributesEnum.Telphone.index();
    public static final int ZIPCODE = AttributesEnum.ZipCode.index();
    public static final int DETAILLOC = AttributesEnum.DetailLoc.index();
    public static final int LANCEEXP = AttributesEnum.LanceExp.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LancerLocationListVORowImpl() {
    }

    /**
     * Gets LancerLocationListEO entity object.
     * @return the LancerLocationListEO
     */
    public BaseEntityImpl getLancerLocationListEO() {
        return (BaseEntityImpl) getEntity(ENTITY_LANCERLOCATIONLISTEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for AREA_ID using the alias name AreaId.
     * @return the AREA_ID
     */
    public String getAreaId() {
        return (String) getAttributeInternal(AREAID);
    }

    /**
     * Sets <code>value</code> as attribute value for AREA_ID using the alias name AreaId.
     * @param value value to set the AREA_ID
     */
    public void setAreaId(String value) {
        setAttributeInternal(AREAID, value);
    }

    /**
     * Gets the attribute value for CITY_ID using the alias name CityId.
     * @return the CITY_ID
     */
    public String getCityId() {
        return (String) getAttributeInternal(CITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_ID using the alias name CityId.
     * @param value value to set the CITY_ID
     */
    public void setCityId(String value) {
        setAttributeInternal(CITYID, value);
    }

    /**
     * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
     * @return the COUNTRY_ID
     */
    public String getCountryId() {
        return (String) getAttributeInternal(COUNTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
     * @param value value to set the COUNTRY_ID
     */
    public void setCountryId(String value) {
        setAttributeInternal(COUNTRYID, value);
    }

    /**
     * Gets the attribute value for CURRENT_IN using the alias name CurrentIn.
     * @return the CURRENT_IN
     */
    public Integer getCurrentIn() {
        return (Integer) getAttributeInternal(CURRENTIN);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_IN using the alias name CurrentIn.
     * @param value value to set the CURRENT_IN
     */
    public void setCurrentIn(Integer value) {
        setAttributeInternal(CURRENTIN, value);
    }

    /**
     * Gets the attribute value for FAX_NUMBER using the alias name FaxNumber.
     * @return the FAX_NUMBER
     */
    public String getFaxNumber() {
        return (String) getAttributeInternal(FAXNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for FAX_NUMBER using the alias name FaxNumber.
     * @param value value to set the FAX_NUMBER
     */
    public void setFaxNumber(String value) {
        setAttributeInternal(FAXNUMBER, value);
    }

    /**
     * Gets the attribute value for LANCER_ID using the alias name LancerId.
     * @return the LANCER_ID
     */
    public String getLancerId() {
        return (String) getAttributeInternal(LANCERID);
    }

    /**
     * Sets <code>value</code> as attribute value for LANCER_ID using the alias name LancerId.
     * @param value value to set the LANCER_ID
     */
    public void setLancerId(String value) {
        setAttributeInternal(LANCERID, value);
    }

    /**
     * Gets the attribute value for PROVINCE_ID using the alias name ProvinceId.
     * @return the PROVINCE_ID
     */
    public String getProvinceId() {
        return (String) getAttributeInternal(PROVINCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROVINCE_ID using the alias name ProvinceId.
     * @param value value to set the PROVINCE_ID
     */
    public void setProvinceId(String value) {
        setAttributeInternal(PROVINCEID, value);
    }

    /**
     * Gets the attribute value for REGION_ID using the alias name RegionId.
     * @return the REGION_ID
     */
    public String getRegionId() {
        return (String) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_ID using the alias name RegionId.
     * @param value value to set the REGION_ID
     */
    public void setRegionId(String value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for TELPHONE using the alias name Telphone.
     * @return the TELPHONE
     */
    public String getTelphone() {
        return (String) getAttributeInternal(TELPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for TELPHONE using the alias name Telphone.
     * @param value value to set the TELPHONE
     */
    public void setTelphone(String value) {
        setAttributeInternal(TELPHONE, value);
    }

    /**
     * Gets the attribute value for ZIP_CODE using the alias name ZipCode.
     * @return the ZIP_CODE
     */
    public String getZipCode() {
        return (String) getAttributeInternal(ZIPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ZIP_CODE using the alias name ZipCode.
     * @param value value to set the ZIP_CODE
     */
    public void setZipCode(String value) {
        setAttributeInternal(ZIPCODE, value);
    }

    /**
     * Gets the attribute value for DETAIL_LOC using the alias name DetailLoc.
     * @return the DETAIL_LOC
     */
    public String getDetailLoc() {
        return (String) getAttributeInternal(DETAILLOC);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL_LOC using the alias name DetailLoc.
     * @param value value to set the DETAIL_LOC
     */
    public void setDetailLoc(String value) {
        setAttributeInternal(DETAILLOC, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link LanceExp.
     */
    public RowIterator getLanceExp() {
        return (RowIterator) getAttributeInternal(LANCEEXP);
    }
}

