package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 12 14:02:52 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationCityVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_LOCATIONCITYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        CityCode,
        CityName,
        ProvinceCode;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int CITYCODE = AttributesEnum.CityCode.index();
    public static final int CITYNAME = AttributesEnum.CityName.index();
    public static final int PROVINCECODE = AttributesEnum.ProvinceCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LocationCityVORowImpl() {
    }

    /**
     * Gets LocationCityEO entity object.
     * @return the LocationCityEO
     */
    public BaseEntityImpl getLocationCityEO() {
        return (BaseEntityImpl) getEntity(ENTITY_LOCATIONCITYEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for CITY_CODE using the alias name CityCode.
     * @return the CITY_CODE
     */
    public String getCityCode() {
        return (String) getAttributeInternal(CITYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_CODE using the alias name CityCode.
     * @param value value to set the CITY_CODE
     */
    public void setCityCode(String value) {
        setAttributeInternal(CITYCODE, value);
    }

    /**
     * Gets the attribute value for CITY_NAME using the alias name CityName.
     * @return the CITY_NAME
     */
    public String getCityName() {
        return (String) getAttributeInternal(CITYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY_NAME using the alias name CityName.
     * @param value value to set the CITY_NAME
     */
    public void setCityName(String value) {
        setAttributeInternal(CITYNAME, value);
    }

    /**
     * Gets the attribute value for PROVINCE_CODE using the alias name ProvinceCode.
     * @return the PROVINCE_CODE
     */
    public String getProvinceCode() {
        return (String) getAttributeInternal(PROVINCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROVINCE_CODE using the alias name ProvinceCode.
     * @param value value to set the PROVINCE_CODE
     */
    public void setProvinceCode(String value) {
        setAttributeInternal(PROVINCECODE, value);
    }
}

