package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 12 14:02:43 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationRegionVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_LOCATIONREGIONEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        NameCn,
        NameEn;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int NAMECN = AttributesEnum.NameCn.index();
    public static final int NAMEEN = AttributesEnum.NameEn.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LocationRegionVORowImpl() {
    }

    /**
     * Gets LocationRegionEO entity object.
     * @return the LocationRegionEO
     */
    public BaseEntityImpl getLocationRegionEO() {
        return (BaseEntityImpl) getEntity(ENTITY_LOCATIONREGIONEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for NAME_CN using the alias name NameCn.
     * @return the NAME_CN
     */
    public String getNameCn() {
        return (String) getAttributeInternal(NAMECN);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_CN using the alias name NameCn.
     * @param value value to set the NAME_CN
     */
    public void setNameCn(String value) {
        setAttributeInternal(NAMECN, value);
    }

    /**
     * Gets the attribute value for NAME_EN using the alias name NameEn.
     * @return the NAME_EN
     */
    public String getNameEn() {
        return (String) getAttributeInternal(NAMEEN);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_EN using the alias name NameEn.
     * @param value value to set the NAME_EN
     */
    public void setNameEn(String value) {
        setAttributeInternal(NAMEEN, value);
    }
}

