package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 18 22:54:03 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostJobsVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PostJobsVOImpl() {
    }
    



    /**
     * Returns the variable value for pUuid.
     * @return variable value for pUuid
     */
    public String getpUuid() {
        return (String) ensureVariableManager().getVariableValue("pUuid");
    }

    /**
     * Sets <code>value</code> for variable pUuid.
     * @param value value to bind as pUuid
     */
    public void setpUuid(String value) {
        ensureVariableManager().setVariableValue("pUuid", value);
    }

    /**
     * Returns the variable value for pCreateBy.
     * @return variable value for pCreateBy
     */
    public String getpCreateBy() {
        return (String) ensureVariableManager().getVariableValue("pCreateBy");
    }

    /**
     * Sets <code>value</code> for variable pCreateBy.
     * @param value value to bind as pCreateBy
     */
    public void setpCreateBy(String value) {
        ensureVariableManager().setVariableValue("pCreateBy", value);
    }

    /**
     * Returns the variable value for pLocation.
     * @return variable value for pLocation
     */
    public String getpLocation() {
        return (String) ensureVariableManager().getVariableValue("pLocation");
    }

    /**
     * Sets <code>value</code> for variable pLocation.
     * @param value value to bind as pLocation
     */
    public void setpLocation(String value) {
        ensureVariableManager().setVariableValue("pLocation", value);
    }

    /**
     * Returns the variable value for pSkill.
     * @return variable value for pSkill
     */
    public String getpSkill() {
        return (String) ensureVariableManager().getVariableValue("pSkill");
    }

    /**
     * Sets <code>value</code> for variable pSkill.
     * @param value value to bind as pSkill
     */
    public void setpSkill(String value) {
        ensureVariableManager().setVariableValue("pSkill", value);
    }

    /**
     * Returns the variable value for pCategory.
     * @return variable value for pCategory
     */
    public String getpCategory() {
        return (String) ensureVariableManager().getVariableValue("pCategory");
    }

    /**
     * Sets <code>value</code> for variable pCategory.
     * @param value value to bind as pCategory
     */
    public void setpCategory(String value) {
        ensureVariableManager().setVariableValue("pCategory", value);
    }
}

