package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 03 11:09:01 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SpreadHeardFromVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_SPREADHEARDFROMEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        Text;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int TEXT = AttributesEnum.Text.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SpreadHeardFromVORowImpl() {
    }

    /**
     * Gets SpreadHeardFromEO entity object.
     * @return the SpreadHeardFromEO
     */
    public BaseEntityImpl getSpreadHeardFromEO() {
        return (BaseEntityImpl) getEntity(ENTITY_SPREADHEARDFROMEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for TEXT using the alias name Text.
     * @return the TEXT
     */
    public String getText() {
        return (String) getAttributeInternal(TEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for TEXT using the alias name Text.
     * @param value value to set the TEXT
     */
    public void setText(String value) {
        setAttributeInternal(TEXT, value);
    }
}

