package com.lance.model.user.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 13 15:14:55 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserEducationVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_USEREDUCATIONEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        UserName,
        InstitutionName,
        DegreeType,
        StartDate,
        EndDate,
        Description,
        Attach1Link,
        Attach2Link,
        Attach3Link,
        TobeVerified,
        DoneVerified,
        Display,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int INSTITUTIONNAME = AttributesEnum.InstitutionName.index();
    public static final int DEGREETYPE = AttributesEnum.DegreeType.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int ATTACH1LINK = AttributesEnum.Attach1Link.index();
    public static final int ATTACH2LINK = AttributesEnum.Attach2Link.index();
    public static final int ATTACH3LINK = AttributesEnum.Attach3Link.index();
    public static final int TOBEVERIFIED = AttributesEnum.TobeVerified.index();
    public static final int DONEVERIFIED = AttributesEnum.DoneVerified.index();
    public static final int DISPLAY = AttributesEnum.Display.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserEducationVORowImpl() {
    }

    /**
     * Gets UserEducationEO entity object.
     * @return the UserEducationEO
     */
    public BaseEntityImpl getUserEducationEO() {
        return (BaseEntityImpl) getEntity(ENTITY_USEREDUCATIONEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for INSTITUTION_NAME using the alias name InstitutionName.
     * @return the INSTITUTION_NAME
     */
    public String getInstitutionName() {
        return (String) getAttributeInternal(INSTITUTIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTITUTION_NAME using the alias name InstitutionName.
     * @param value value to set the INSTITUTION_NAME
     */
    public void setInstitutionName(String value) {
        setAttributeInternal(INSTITUTIONNAME, value);
    }

    /**
     * Gets the attribute value for DEGREE_TYPE using the alias name DegreeType.
     * @return the DEGREE_TYPE
     */
    public String getDegreeType() {
        return (String) getAttributeInternal(DEGREETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEGREE_TYPE using the alias name DegreeType.
     * @param value value to set the DEGREE_TYPE
     */
    public void setDegreeType(String value) {
        setAttributeInternal(DEGREETYPE, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public ClobDomain getDescription() {
        return (ClobDomain) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(ClobDomain value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ATTACH1_LINK using the alias name Attach1Link.
     * @return the ATTACH1_LINK
     */
    public String getAttach1Link() {
        return (String) getAttributeInternal(ATTACH1LINK);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH1_LINK using the alias name Attach1Link.
     * @param value value to set the ATTACH1_LINK
     */
    public void setAttach1Link(String value) {
        setAttributeInternal(ATTACH1LINK, value);
    }

    /**
     * Gets the attribute value for ATTACH2_LINK using the alias name Attach2Link.
     * @return the ATTACH2_LINK
     */
    public String getAttach2Link() {
        return (String) getAttributeInternal(ATTACH2LINK);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH2_LINK using the alias name Attach2Link.
     * @param value value to set the ATTACH2_LINK
     */
    public void setAttach2Link(String value) {
        setAttributeInternal(ATTACH2LINK, value);
    }

    /**
     * Gets the attribute value for ATTACH3_LINK using the alias name Attach3Link.
     * @return the ATTACH3_LINK
     */
    public String getAttach3Link() {
        return (String) getAttributeInternal(ATTACH3LINK);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH3_LINK using the alias name Attach3Link.
     * @param value value to set the ATTACH3_LINK
     */
    public void setAttach3Link(String value) {
        setAttributeInternal(ATTACH3LINK, value);
    }

    /**
     * Gets the attribute value for TOBE_VERIFIED using the alias name TobeVerified.
     * @return the TOBE_VERIFIED
     */
    public BigDecimal getTobeVerified() {
        return (BigDecimal) getAttributeInternal(TOBEVERIFIED);
    }

    /**
     * Sets <code>value</code> as attribute value for TOBE_VERIFIED using the alias name TobeVerified.
     * @param value value to set the TOBE_VERIFIED
     */
    public void setTobeVerified(BigDecimal value) {
        setAttributeInternal(TOBEVERIFIED, value);
    }

    /**
     * Gets the attribute value for DONE_VERIFIED using the alias name DoneVerified.
     * @return the DONE_VERIFIED
     */
    public BigDecimal getDoneVerified() {
        return (BigDecimal) getAttributeInternal(DONEVERIFIED);
    }

    /**
     * Sets <code>value</code> as attribute value for DONE_VERIFIED using the alias name DoneVerified.
     * @param value value to set the DONE_VERIFIED
     */
    public void setDoneVerified(BigDecimal value) {
        setAttributeInternal(DONEVERIFIED, value);
    }

    /**
     * Gets the attribute value for DISPLAY using the alias name Display.
     * @return the DISPLAY
     */
    public BigDecimal getDisplay() {
        return (BigDecimal) getAttributeInternal(DISPLAY);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAY using the alias name Display.
     * @param value value to set the DISPLAY
     */
    public void setDisplay(BigDecimal value) {
        setAttributeInternal(DISPLAY, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Date getCreateOn() {
        return (Date) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Date value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_BY using the alias name ModifyBy.
     * @param value value to set the MODIFY_BY
     */
    public void setModifyBy(String value) {
        setAttributeInternal(MODIFYBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Date getModifyOn() {
        return (Date) getAttributeInternal(MODIFYON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_ON using the alias name ModifyOn.
     * @param value value to set the MODIFY_ON
     */
    public void setModifyOn(Date value) {
        setAttributeInternal(MODIFYON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }
}

