package com.lance.model.user.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 13 15:14:43 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserSkillVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_USERSKILLEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        UserName,
        Name,
        Tested,
        Display,
        ShowOrder,
        MasterLevel,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int TESTED = AttributesEnum.Tested.index();
    public static final int DISPLAY = AttributesEnum.Display.index();
    public static final int SHOWORDER = AttributesEnum.ShowOrder.index();
    public static final int MASTERLEVEL = AttributesEnum.MasterLevel.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UserSkillVORowImpl() {
    }

    /**
     * Gets UserSkillEO entity object.
     * @return the UserSkillEO
     */
    public BaseEntityImpl getUserSkillEO() {
        return (BaseEntityImpl) getEntity(ENTITY_USERSKILLEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for TESTED using the alias name Tested.
     * @return the TESTED
     */
    public BigDecimal getTested() {
        return (BigDecimal) getAttributeInternal(TESTED);
    }

    /**
     * Sets <code>value</code> as attribute value for TESTED using the alias name Tested.
     * @param value value to set the TESTED
     */
    public void setTested(BigDecimal value) {
        setAttributeInternal(TESTED, value);
    }

    /**
     * Gets the attribute value for DISPLAY using the alias name Display.
     * @return the DISPLAY
     */
    public BigDecimal getDisplay() {
        return (BigDecimal) getAttributeInternal(DISPLAY);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAY using the alias name Display.
     * @param value value to set the DISPLAY
     */
    public void setDisplay(BigDecimal value) {
        setAttributeInternal(DISPLAY, value);
    }

    /**
     * Gets the attribute value for SHOW_ORDER using the alias name ShowOrder.
     * @return the SHOW_ORDER
     */
    public BigDecimal getShowOrder() {
        return (BigDecimal) getAttributeInternal(SHOWORDER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHOW_ORDER using the alias name ShowOrder.
     * @param value value to set the SHOW_ORDER
     */
    public void setShowOrder(BigDecimal value) {
        setAttributeInternal(SHOWORDER, value);
    }

    /**
     * Gets the attribute value for MASTER_LEVEL using the alias name MasterLevel.
     * @return the MASTER_LEVEL
     */
    public BigDecimal getMasterLevel() {
        return (BigDecimal) getAttributeInternal(MASTERLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for MASTER_LEVEL using the alias name MasterLevel.
     * @param value value to set the MASTER_LEVEL
     */
    public void setMasterLevel(BigDecimal value) {
        setAttributeInternal(MASTERLEVEL, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Date getCreateOn() {
        return (Date) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Date value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_BY using the alias name ModifyBy.
     * @param value value to set the MODIFY_BY
     */
    public void setModifyBy(String value) {
        setAttributeInternal(MODIFYBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Date getModifyOn() {
        return (Date) getAttributeInternal(MODIFYON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_ON using the alias name ModifyOn.
     * @param value value to set the MODIFY_ON
     */
    public void setModifyOn(Date value) {
        setAttributeInternal(MODIFYON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }
}

