package com.lance.model.user.vo;

import com.lance.model.vo.CompanyVORowImpl;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 13 15:14:23 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UUserVORowImpl extends BaseViewRowImpl {


    public static final int ENTITY_UUSEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserName,
        TrueName,
        DisplayName,
        Email,
        Password,
        Img,
        Country,
        AccountType,
        CompanyId,
        PhoneNumber,
        Attach,
        JobTitle,
        Video,
        Description,
        WebsiteUrl,
        ImNumberA,
        ImTypeA,
        ImNumberB,
        ImTypeB,
        ImNumberC,
        ImTypeC,
        LocationA,
        LocationB,
        Tagline,
        HourlyRate,
        ChargeRate,
        Overview,
        ServiceDescription,
        PaymentTerms,
        Keywords,
        AddressDisplay,
        ContactInfo,
        IdentityType,
        IdentityNo,
        Rank,
        RankDesc,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version,
        LastLoginTime,
        CompanyName,
        CanBeSearch,
        DefaultRole,
        UserSkill,
        UserEducation,
        UserLocationList,
        Company;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int TRUENAME = AttributesEnum.TrueName.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int IMG = AttributesEnum.Img.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int ACCOUNTTYPE = AttributesEnum.AccountType.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int ATTACH = AttributesEnum.Attach.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int VIDEO = AttributesEnum.Video.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int WEBSITEURL = AttributesEnum.WebsiteUrl.index();
    public static final int IMNUMBERA = AttributesEnum.ImNumberA.index();
    public static final int IMTYPEA = AttributesEnum.ImTypeA.index();
    public static final int IMNUMBERB = AttributesEnum.ImNumberB.index();
    public static final int IMTYPEB = AttributesEnum.ImTypeB.index();
    public static final int IMNUMBERC = AttributesEnum.ImNumberC.index();
    public static final int IMTYPEC = AttributesEnum.ImTypeC.index();
    public static final int LOCATIONA = AttributesEnum.LocationA.index();
    public static final int LOCATIONB = AttributesEnum.LocationB.index();
    public static final int TAGLINE = AttributesEnum.Tagline.index();
    public static final int HOURLYRATE = AttributesEnum.HourlyRate.index();
    public static final int CHARGERATE = AttributesEnum.ChargeRate.index();
    public static final int OVERVIEW = AttributesEnum.Overview.index();
    public static final int SERVICEDESCRIPTION = AttributesEnum.ServiceDescription.index();
    public static final int PAYMENTTERMS = AttributesEnum.PaymentTerms.index();
    public static final int KEYWORDS = AttributesEnum.Keywords.index();
    public static final int ADDRESSDISPLAY = AttributesEnum.AddressDisplay.index();
    public static final int CONTACTINFO = AttributesEnum.ContactInfo.index();
    public static final int IDENTITYTYPE = AttributesEnum.IdentityType.index();
    public static final int IDENTITYNO = AttributesEnum.IdentityNo.index();
    public static final int RANK = AttributesEnum.Rank.index();
    public static final int RANKDESC = AttributesEnum.RankDesc.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int LASTLOGINTIME = AttributesEnum.LastLoginTime.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int CANBESEARCH = AttributesEnum.CanBeSearch.index();
    public static final int DEFAULTROLE = AttributesEnum.DefaultRole.index();
    public static final int USERSKILL = AttributesEnum.UserSkill.index();
    public static final int USEREDUCATION = AttributesEnum.UserEducation.index();
    public static final int USERLOCATIONLIST = AttributesEnum.UserLocationList.index();
    public static final int COMPANY = AttributesEnum.Company.index();

    /**
     * This is the default constructor (do not remove).
     */
    public UUserVORowImpl() {
    }

    /**
     * Gets UUserEO entity object.
     * @return the UUserEO
     */
    public BaseEntityImpl getUUserEO() {
        return (BaseEntityImpl) getEntity(ENTITY_UUSEREO);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for TRUE_NAME using the alias name TrueName.
     * @return the TRUE_NAME
     */
    public String getTrueName() {
        return (String) getAttributeInternal(TRUENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRUE_NAME using the alias name TrueName.
     * @param value value to set the TRUE_NAME
     */
    public void setTrueName(String value) {
        setAttributeInternal(TRUENAME, value);
    }

    /**
     * Gets the attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @return the DISPLAY_NAME
     */
    public String getDisplayName() {
        return (String) getAttributeInternal(DISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @param value value to set the DISPLAY_NAME
     */
    public void setDisplayName(String value) {
        setAttributeInternal(DISPLAYNAME, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for IMG using the alias name Img.
     * @return the IMG
     */
    public String getImg() {
        return (String) getAttributeInternal(IMG);
    }

    /**
     * Sets <code>value</code> as attribute value for IMG using the alias name Img.
     * @param value value to set the IMG
     */
    public void setImg(String value) {
        setAttributeInternal(IMG, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for ACCOUNT_TYPE using the alias name AccountType.
     * @return the ACCOUNT_TYPE
     */
    public String getAccountType() {
        return (String) getAttributeInternal(ACCOUNTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCOUNT_TYPE using the alias name AccountType.
     * @param value value to set the ACCOUNT_TYPE
     */
    public void setAccountType(String value) {
        setAttributeInternal(ACCOUNTTYPE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public String getCompanyId() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @return the PHONE_NUMBER
     */
    public String getPhoneNumber() {
        return (String) getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NUMBER using the alias name PhoneNumber.
     * @param value value to set the PHONE_NUMBER
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for ATTACH using the alias name Attach.
     * @return the ATTACH
     */
    public String getAttach() {
        return (String) getAttributeInternal(ATTACH);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH using the alias name Attach.
     * @param value value to set the ATTACH
     */
    public void setAttach(String value) {
        setAttributeInternal(ATTACH, value);
    }

    /**
     * Gets the attribute value for JOB_TITLE using the alias name JobTitle.
     * @return the JOB_TITLE
     */
    public String getJobTitle() {
        return (String) getAttributeInternal(JOBTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TITLE using the alias name JobTitle.
     * @param value value to set the JOB_TITLE
     */
    public void setJobTitle(String value) {
        setAttributeInternal(JOBTITLE, value);
    }

    /**
     * Gets the attribute value for VIDEO using the alias name Video.
     * @return the VIDEO
     */
    public String getVideo() {
        return (String) getAttributeInternal(VIDEO);
    }

    /**
     * Sets <code>value</code> as attribute value for VIDEO using the alias name Video.
     * @param value value to set the VIDEO
     */
    public void setVideo(String value) {
        setAttributeInternal(VIDEO, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public ClobDomain getDescription() {
        return (ClobDomain) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(ClobDomain value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for WEBSITE_URL using the alias name WebsiteUrl.
     * @return the WEBSITE_URL
     */
    public String getWebsiteUrl() {
        return (String) getAttributeInternal(WEBSITEURL);
    }

    /**
     * Sets <code>value</code> as attribute value for WEBSITE_URL using the alias name WebsiteUrl.
     * @param value value to set the WEBSITE_URL
     */
    public void setWebsiteUrl(String value) {
        setAttributeInternal(WEBSITEURL, value);
    }

    /**
     * Gets the attribute value for IM_NUMBER_A using the alias name ImNumberA.
     * @return the IM_NUMBER_A
     */
    public String getImNumberA() {
        return (String) getAttributeInternal(IMNUMBERA);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_NUMBER_A using the alias name ImNumberA.
     * @param value value to set the IM_NUMBER_A
     */
    public void setImNumberA(String value) {
        setAttributeInternal(IMNUMBERA, value);
    }

    /**
     * Gets the attribute value for IM_TYPE_A using the alias name ImTypeA.
     * @return the IM_TYPE_A
     */
    public String getImTypeA() {
        return (String) getAttributeInternal(IMTYPEA);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_TYPE_A using the alias name ImTypeA.
     * @param value value to set the IM_TYPE_A
     */
    public void setImTypeA(String value) {
        setAttributeInternal(IMTYPEA, value);
    }

    /**
     * Gets the attribute value for IM_NUMBER_B using the alias name ImNumberB.
     * @return the IM_NUMBER_B
     */
    public String getImNumberB() {
        return (String) getAttributeInternal(IMNUMBERB);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_NUMBER_B using the alias name ImNumberB.
     * @param value value to set the IM_NUMBER_B
     */
    public void setImNumberB(String value) {
        setAttributeInternal(IMNUMBERB, value);
    }

    /**
     * Gets the attribute value for IM_TYPE_B using the alias name ImTypeB.
     * @return the IM_TYPE_B
     */
    public String getImTypeB() {
        return (String) getAttributeInternal(IMTYPEB);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_TYPE_B using the alias name ImTypeB.
     * @param value value to set the IM_TYPE_B
     */
    public void setImTypeB(String value) {
        setAttributeInternal(IMTYPEB, value);
    }

    /**
     * Gets the attribute value for IM_NUMBER_C using the alias name ImNumberC.
     * @return the IM_NUMBER_C
     */
    public String getImNumberC() {
        return (String) getAttributeInternal(IMNUMBERC);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_NUMBER_C using the alias name ImNumberC.
     * @param value value to set the IM_NUMBER_C
     */
    public void setImNumberC(String value) {
        setAttributeInternal(IMNUMBERC, value);
    }

    /**
     * Gets the attribute value for IM_TYPE_C using the alias name ImTypeC.
     * @return the IM_TYPE_C
     */
    public String getImTypeC() {
        return (String) getAttributeInternal(IMTYPEC);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_TYPE_C using the alias name ImTypeC.
     * @param value value to set the IM_TYPE_C
     */
    public void setImTypeC(String value) {
        setAttributeInternal(IMTYPEC, value);
    }

    /**
     * Gets the attribute value for LOCATION_A using the alias name LocationA.
     * @return the LOCATION_A
     */
    public String getLocationA() {
        return (String) getAttributeInternal(LOCATIONA);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_A using the alias name LocationA.
     * @param value value to set the LOCATION_A
     */
    public void setLocationA(String value) {
        setAttributeInternal(LOCATIONA, value);
    }

    /**
     * Gets the attribute value for LOCATION_B using the alias name LocationB.
     * @return the LOCATION_B
     */
    public String getLocationB() {
        return (String) getAttributeInternal(LOCATIONB);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_B using the alias name LocationB.
     * @param value value to set the LOCATION_B
     */
    public void setLocationB(String value) {
        setAttributeInternal(LOCATIONB, value);
    }

    /**
     * Gets the attribute value for TAGLINE using the alias name Tagline.
     * @return the TAGLINE
     */
    public String getTagline() {
        return (String) getAttributeInternal(TAGLINE);
    }

    /**
     * Sets <code>value</code> as attribute value for TAGLINE using the alias name Tagline.
     * @param value value to set the TAGLINE
     */
    public void setTagline(String value) {
        setAttributeInternal(TAGLINE, value);
    }

    /**
     * Gets the attribute value for HOURLY_RATE using the alias name HourlyRate.
     * @return the HOURLY_RATE
     */
    public BigDecimal getHourlyRate() {
        return (BigDecimal) getAttributeInternal(HOURLYRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for HOURLY_RATE using the alias name HourlyRate.
     * @param value value to set the HOURLY_RATE
     */
    public void setHourlyRate(BigDecimal value) {
        setAttributeInternal(HOURLYRATE, value);
    }

    /**
     * Gets the attribute value for CHARGE_RATE using the alias name ChargeRate.
     * @return the CHARGE_RATE
     */
    public BigDecimal getChargeRate() {
        return (BigDecimal) getAttributeInternal(CHARGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CHARGE_RATE using the alias name ChargeRate.
     * @param value value to set the CHARGE_RATE
     */
    public void setChargeRate(BigDecimal value) {
        setAttributeInternal(CHARGERATE, value);
    }

    /**
     * Gets the attribute value for OVERVIEW using the alias name Overview.
     * @return the OVERVIEW
     */
    public String getOverview() {
        return (String) getAttributeInternal(OVERVIEW);
    }

    /**
     * Sets <code>value</code> as attribute value for OVERVIEW using the alias name Overview.
     * @param value value to set the OVERVIEW
     */
    public void setOverview(String value) {
        setAttributeInternal(OVERVIEW, value);
    }

    /**
     * Gets the attribute value for SERVICE_DESCRIPTION using the alias name ServiceDescription.
     * @return the SERVICE_DESCRIPTION
     */
    public ClobDomain getServiceDescription() {
        return (ClobDomain) getAttributeInternal(SERVICEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for SERVICE_DESCRIPTION using the alias name ServiceDescription.
     * @param value value to set the SERVICE_DESCRIPTION
     */
    public void setServiceDescription(ClobDomain value) {
        setAttributeInternal(SERVICEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for PAYMENT_TERMS using the alias name PaymentTerms.
     * @return the PAYMENT_TERMS
     */
    public ClobDomain getPaymentTerms() {
        return (ClobDomain) getAttributeInternal(PAYMENTTERMS);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_TERMS using the alias name PaymentTerms.
     * @param value value to set the PAYMENT_TERMS
     */
    public void setPaymentTerms(ClobDomain value) {
        setAttributeInternal(PAYMENTTERMS, value);
    }

    /**
     * Gets the attribute value for KEYWORDS using the alias name Keywords.
     * @return the KEYWORDS
     */
    public String getKeywords() {
        return (String) getAttributeInternal(KEYWORDS);
    }

    /**
     * Sets <code>value</code> as attribute value for KEYWORDS using the alias name Keywords.
     * @param value value to set the KEYWORDS
     */
    public void setKeywords(String value) {
        setAttributeInternal(KEYWORDS, value);
    }

    /**
     * Gets the attribute value for ADDRESS_DISPLAY using the alias name AddressDisplay.
     * @return the ADDRESS_DISPLAY
     */
    public String getAddressDisplay() {
        return (String) getAttributeInternal(ADDRESSDISPLAY);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_DISPLAY using the alias name AddressDisplay.
     * @param value value to set the ADDRESS_DISPLAY
     */
    public void setAddressDisplay(String value) {
        setAttributeInternal(ADDRESSDISPLAY, value);
    }

    /**
     * Gets the attribute value for CONTACT_INFO using the alias name ContactInfo.
     * @return the CONTACT_INFO
     */
    public String getContactInfo() {
        return (String) getAttributeInternal(CONTACTINFO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_INFO using the alias name ContactInfo.
     * @param value value to set the CONTACT_INFO
     */
    public void setContactInfo(String value) {
        setAttributeInternal(CONTACTINFO, value);
    }

    /**
     * Gets the attribute value for IDENTITY_TYPE using the alias name IdentityType.
     * @return the IDENTITY_TYPE
     */
    public String getIdentityType() {
        return (String) getAttributeInternal(IDENTITYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for IDENTITY_TYPE using the alias name IdentityType.
     * @param value value to set the IDENTITY_TYPE
     */
    public void setIdentityType(String value) {
        setAttributeInternal(IDENTITYTYPE, value);
    }

    /**
     * Gets the attribute value for IDENTITY_NO using the alias name IdentityNo.
     * @return the IDENTITY_NO
     */
    public String getIdentityNo() {
        return (String) getAttributeInternal(IDENTITYNO);
    }

    /**
     * Sets <code>value</code> as attribute value for IDENTITY_NO using the alias name IdentityNo.
     * @param value value to set the IDENTITY_NO
     */
    public void setIdentityNo(String value) {
        setAttributeInternal(IDENTITYNO, value);
    }

    /**
     * Gets the attribute value for RANK_DESC using the alias name RankDesc.
     * @return the RANK_DESC
     */
    public String getRankDesc() {
        return (String) getAttributeInternal(RANKDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for RANK_DESC using the alias name RankDesc.
     * @param value value to set the RANK_DESC
     */
    public void setRankDesc(String value) {
        setAttributeInternal(RANKDESC, value);
    }

    /**
     * Gets the attribute value for RANK using the alias name Rank.
     * @return the RANK
     */
    public BigDecimal getRank() {
        return (BigDecimal) getAttributeInternal(RANK);
    }

    /**
     * Sets <code>value</code> as attribute value for RANK using the alias name Rank.
     * @param value value to set the RANK
     */
    public void setRank(BigDecimal value) {
        setAttributeInternal(RANK, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }


    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Date getCreateOn() {
        return (Date) getAttributeInternal(CREATEON);
    }


    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }


    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Date getModifyOn() {
        return (Date) getAttributeInternal(MODIFYON);
    }


    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }


    /**
     * Gets the attribute value for LAST_LOGIN_TIME using the alias name LastLoginTime.
     * @return the LAST_LOGIN_TIME
     */
    public Date getLastLoginTime() {
        return (Date) getAttributeInternal(LASTLOGINTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_LOGIN_TIME using the alias name LastLoginTime.
     * @param value value to set the LAST_LOGIN_TIME
     */
    public void setLastLoginTime(Date value) {
        setAttributeInternal(LASTLOGINTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyName.
     * @return the CompanyName
     */
    public String getCompanyName() {
        CompanyVORowImpl row = ((CompanyVORowImpl) this.getCompany());
        if (row == null) {
            return null;
        } else {
            return row.getName();
        }
        //        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyName.
     * @param value value to set the  CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for CAN_BE_SEARCH using the alias name CanBeSearch.
     * @return the CAN_BE_SEARCH
     */
    public BigDecimal getCanBeSearch() {
        return (BigDecimal) getAttributeInternal(CANBESEARCH);
    }

    /**
     * Sets <code>value</code> as attribute value for CAN_BE_SEARCH using the alias name CanBeSearch.
     * @param value value to set the CAN_BE_SEARCH
     */
    public void setCanBeSearch(BigDecimal value) {
        setAttributeInternal(CANBESEARCH, value);
    }

    /**
     * Gets the attribute value for DEFAULT_ROLE using the alias name DefaultRole.
     * @return the DEFAULT_ROLE
     */
    public String getDefaultRole() {
        return (String) getAttributeInternal(DEFAULTROLE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEFAULT_ROLE using the alias name DefaultRole.
     * @param value value to set the DEFAULT_ROLE
     */
    public void setDefaultRole(String value) {
        setAttributeInternal(DEFAULTROLE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UserSkill.
     */
    public RowIterator getUserSkill() {
        return (RowIterator) getAttributeInternal(USERSKILL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UserEducation.
     */
    public RowIterator getUserEducation() {
        return (RowIterator) getAttributeInternal(USEREDUCATION);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link UserLocationList.
     */
    public RowIterator getUserLocationList() {
        return (RowIterator) getAttributeInternal(USERLOCATIONLIST);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link Company.
     */
    public Row getCompany() {
        return (Row) getAttributeInternal(COMPANY);
    }

    /**
     * Sets the master-detail link Company between this object and <code>value</code>.
     */
    public void setCompany(Row value) {
        setAttributeInternal(COMPANY, value);
    }
}

