package com.lance.model.vvo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 30 11:25:14 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractClientReportVVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractClientReportVVOImpl() {
    }

    /**
     * Returns the bind variable value for startDate.
     * @return bind variable value for startDate
     */
    public String getstartDate() {
        return (String) getNamedWhereClauseParam("startDate");
    }

    /**
     * Sets <code>value</code> for bind variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(String value) {
        setNamedWhereClauseParam("startDate", value);
    }

    /**
     * Returns the bind variable value for endDate.
     * @return bind variable value for endDate
     */
    public String getendDate() {
        return (String) getNamedWhereClauseParam("endDate");
    }

    /**
     * Sets <code>value</code> for bind variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(String value) {
        setNamedWhereClauseParam("endDate", value);
    }

    /**
     * Returns the bind variable value for conId.
     * @return bind variable value for conId
     */
    public String getconId() {
        return (String) getNamedWhereClauseParam("conId");
    }

    /**
     * Sets <code>value</code> for bind variable conId.
     * @param value value to bind as conId
     */
    public void setconId(String value) {
        setNamedWhereClauseParam("conId", value);
    }
}

