package com.lance.model.vvo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 21 02:04:26 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationCountryVVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LocationCountryVVOImpl() {
    }

    /**
     * Returns the variable value for pName.
     * @return variable value for pName
     */
    public String getpName() {
        return (String) ensureVariableManager().getVariableValue("pName");
    }

    /**
     * Sets <code>value</code> for variable pName.
     * @param value value to bind as pName
     */
    public void setpName(String value) {
        ensureVariableManager().setVariableValue("pName", value);
    }
}

