package com.lance.model.vvo;

import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 27 16:35:20 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupsVVORowImpl extends BaseViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ItemKey,
        ItemType,
        ItemDisplay,
        ItemDesc,
        CreateBy,
        ModifyBy,
        CreateOn,
        ModifyOn,
        Version;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ITEMKEY = AttributesEnum.ItemKey.index();
    public static final int ITEMTYPE = AttributesEnum.ItemType.index();
    public static final int ITEMDISPLAY = AttributesEnum.ItemDisplay.index();
    public static final int ITEMDESC = AttributesEnum.ItemDesc.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LookupsVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ItemKey.
     * @return the ItemKey
     */
    public String getItemKey() {
        return (String) getAttributeInternal(ITEMKEY);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemDisplay.
     * @return the ItemDisplay
     */
    public String getItemDisplay() {
        return (String) getAttributeInternal(ITEMDISPLAY);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemDesc.
     * @return the ItemDesc
     */
    public String getItemDesc() {
        return (String) getAttributeInternal(ITEMDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemType.
     * @return the ItemType
     */
    public String getItemType() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateBy.
     * @return the CreateBy
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }


    /**
     * Gets the attribute value for the calculated attribute ModifyBy.
     * @return the ModifyBy
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateOn.
     * @return the CreateOn
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }


    /**
     * Gets the attribute value for the calculated attribute ModifyOn.
     * @return the ModifyOn
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }
}

