package com.lance.model.vvo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;

import java.math.BigDecimal;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 20 09:42:45 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostJobsVVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PostJobsVVOImpl() {
    }

    /**
     * Returns the variable value for pStatus.
     * @return variable value for pStatus
     */
    public Integer getpStatus() {
        return (Integer) ensureVariableManager().getVariableValue("pStatus");
    }

    /**
     * Sets <code>value</code> for variable pStatus.
     * @param value value to bind as pStatus
     */
    public void setpStatus(Integer value) {
        ensureVariableManager().setVariableValue("pStatus", value);
    }

    /**
     * Returns the variable value for pName.
     * @return variable value for pName
     */
    public String getpName() {
        return (String) ensureVariableManager().getVariableValue("pName");
    }

    /**
     * Sets <code>value</code> for variable pName.
     * @param value value to bind as pName
     */
    public void setpName(String value) {
        ensureVariableManager().setVariableValue("pName", value);
    }

    /**
     * Returns the variable value for pBrief.
     * @return variable value for pBrief
     */
    public String getpBrief() {
        return (String) ensureVariableManager().getVariableValue("pBrief");
    }

    /**
     * Sets <code>value</code> for variable pBrief.
     * @param value value to bind as pBrief
     */
    public void setpBrief(String value) {
        ensureVariableManager().setVariableValue("pBrief", value);
    }

    /**
     * Returns the variable value for pSkill.
     * @return variable value for pSkill
     */
    public String getpSkill() {
        return (String) ensureVariableManager().getVariableValue("pSkill");
    }

    /**
     * Sets <code>value</code> for variable pSkill.
     * @param value value to bind as pSkill
     */
    public void setpSkill(String value) {
        ensureVariableManager().setVariableValue("pSkill", value);
    }
}

